#!/usr/bin/with-contenv bash

[[ -f /config/nzbget.conf ]] && \
  source /config/nzbget.conf &>/dev/null

[[ -z "${ScriptDir}" ]] || [[ "${ScriptDir}" == "/scripts" ]] && \
  ScriptDir=/config/scripts

[[ ! -e "${ScriptDir}" ]] && \
  mkdir -p "${ScriptDir}"

DIR="${ScriptDir}/M4V-Converter"
[[ ! -L "${DIR}" ]] && \
  ln -s /app/M4V-Converter "${DIR}"

chown abc:abc -R \
  /app/M4V-Converter \
  "${ScriptDir}"
