#!/usr/bin/with-contenv bash

[[ ! -e /config/sabnzbd.ini ]] && \
  cp /defaults/sabnzbd.ini /config/sabnzbd.ini

[[ ! -e /config/M4V-Converter.conf ]] && \
  cp /app/M4V-Converter/default.conf /config/M4V-Converter.conf

[[ -f /config/sabnzbd.ini ]] && \
  source <(cat /config/sabnzbd.ini | grep script_dir | sed 's/\ = \ /=/g') &>/dev/null

[[ -z "${script_dir}" ]] && \
  script_dir=/config/scripts

[[ ! -e "${script_dir}" ]] && \
  mkdir -p "${script_dir}"

FILE="${script_dir}/sabnzbd.sh"
[[ ! -L "${FILE}" ]] && \
  ln -s /app/M4V-Converter/sabnzbd.sh "${FILE}"

chown abc:abc -R \
  /app/M4V-Converter \
  /config/M4V-Converter.conf \
  /config/sabnzbd.ini \
  "${script_dir}"
