#!/usr/bin/env bash

set -ex

curl -sSL https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz | \
tar --strip-components 1 -xvz docker/docker

QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
QEMU_USER_STATIC_LATEST_TAG=$(curl -s https://api.github.com/repos/multiarch/qemu-user-static/tags | grep 'name.*v[0-9]' | head -n 1 | cut -d '"' -f 4)

for ARCH in arm aarch64; do
  curl -sSL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/qemu-${ARCH}-static.tar.gz" | tar xzv
done

exit 0
