#!/usr/bin/env bash

set -ex

declare -A BUILD_ARCH=(\
["amd64"]="amd64" \
["arm32v7"]="arm" \
["arm64v8"]="arm64")

tempdir=$(mktemp -d -t yolo.XXXXXXXX)
cd $tempdir

for ARCH in ${!BUILD_ARCH[@]}; do
  docker save ${DOCKER_REPO}:${ARCH}-${DOCKER_TAG} | tar xv
  for filename in */json; do
    [ -e "$filename" ] || continue
    jq --compact-output 'del(.architecture)' < "$filename" | sponge "$filename"
  done
  for filename in *.json; do
    [ -e "$filename" ] || continue
    ! [ $filename = "manifest.json" ] || continue
    jq --arg architecture "${BUILD_ARCH[${ARCH}]}" \
       --compact-output '.architecture=$architecture' < "$filename" | sponge "$filename"
  done
  tar cv . | docker load
  rm -rf $tempdir/*
done

exit 0
