#!/usr/bin/env bash

set -ex

curl -sSL https://download.docker.com/linux/static/stable/x86_64/docker-19.03.8.tgz | \
tar --strip-components 1 -xvz docker/docker
export DOCKER_CLI_EXPERIMENTAL=enabled

COMMAND=${IMAGE_NAME}
for ARCH in amd64 arm32v7 arm64v8; do
  ./docker manifest create \
  ${DOCKER_REPO}:${ARCH}-${DOCKER_TAG} ${DOCKER_REPO}:${ARCH}-${DOCKER_TAG}
  COMMAND+=" ${DOCKER_REPO}:${ARCH}-${DOCKER_TAG}"
done
./docker manifest create ${COMMAND}

for ARCH in arm32v7 arm64v8; do
  COMMAND=${DOCKER_REPO}:${ARCH}-${DOCKER_TAG}
  case ${ARCH} in
    arm32v7) COMMAND+=" --os linux --arch arm" ;;
    arm64v8) COMMAND+=" --os linux --arch arm64 --variant armv8" ;;
  esac
  ./docker manifest annotate ${IMAGE_NAME} ${COMMAND}
  ./docker manifest annotate ${DOCKER_REPO}:${ARCH}-${DOCKER_TAG} ${COMMAND}
done

./docker manifest push --purge ${IMAGE_NAME}
for ARCH in amd64 arm32v7 arm64v8; do
  ./docker manifest push --purge ${DOCKER_REPO}:${ARCH}-${DOCKER_TAG}
done

exit 0
