#!/usr/bin/env bash

set -ex

export DOCKER_CLI_EXPERIMENTAL=enabled

COMMAND=${IMAGE_NAME}
for ARCH in amd64 arm32v7 arm64v8; do
  COMMAND+=" ${DOCKER_REPO}:${ARCH}-${DOCKER_TAG}"
done
./docker manifest create ${COMMAND}

for ARCH in arm32v7 arm64v8; do
  COMMAND=${DOCKER_REPO}:${ARCH}-${DOCKER_TAG}
  case ${ARCH} in
    arm32v7) COMMAND+=" --os linux --arch arm" ;;
    arm64v8) COMMAND+=" --os linux --arch arm64 --variant armv8" ;;
  esac
  ./docker manifest annotate ${IMAGE_NAME} ${COMMAND}
done

./docker manifest push --purge ${IMAGE_NAME}

exit 0
